language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
install:
  - mvn clean validate
script:
  - mvn deploy --settings deploy-settings.xml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b5f5d5c337a7af9276
    on_success: change
    on_failure: always
    on_start: never
  irc:
    - irc.freenode.org#jrds
