version: 2.1
jobs:
    checkout:
        docker:
            - image: circleci/openjdk:14-jdk-buster
        steps:
            - checkout
            - restore_cache:
                key: jrds-{{ checksum "pom.xml" }}-{{ checksum "jrds-core/pom.xml" }}-{{ checksum "jrds-ipmi/pom.xml" }}-{{ checksum "jrds-jsonp/pom.xml" }}-{{ checksum "jrds-log4j/pom.xml" }}-{{ checksum "jrds-snmp/pom.xml" }}-{{ checksum "jrds-standalone/pom.xml" }}-{{ checksum "jrds-webapp/pom.xml" }}-{{ checksum "jrds-jdbc/pom.xml" }}
            - run:
                command: |
                    sudo apt-get update
                    sudo apt install libsnmp-base
                    mkdir -p /home/circleci/.sonar/cache /home/circleci/.m2/repository
                    mvn -B dependency:go-offline -Psonar,versions -s .circleci/settings.xml -DexcludeGroupIds=fr.jrds
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/jfrog
                    - home/circleci/project
                    - usr/share/snmp/mibs/
    jdk8:
        docker:
            - image: circleci/openjdk:8-buster
        steps:
            - persist_to_workspace:
                root: /usr/local
                paths:
                    - openjdk-8
    build:
        docker:
            - image: circleci/openjdk:14-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: mvn -B clean compile install -DskipTests -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/java/openjdk-14
                    MAVEN_OPTS: "-Xmx2048m"
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/project
    testsj13:
        docker:
            - image: circleci/openjdk:13-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
                    sudo mkdir -p /usr/share/snmp/mibs/
                    sudo mv -n /tmp/ws/usr/share/snmp/mibs/* /usr/share/snmp/mibs/
            - run:
                command: |
                    mvn -B test -Pskip -DargLine="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/java/openjdk-13
                    MAVEN_OPTS: "-Xmx1024m"
            - store_test_results:
                path: target/surefire-reports
            #don't persist_to_workspace, can't be done in parallel with testsj11
    testsj11:
        docker:
            - image: circleci/openjdk:11-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
                    sudo mkdir -p /usr/share/snmp/mibs/
                    sudo mv -n /tmp/ws/usr/share/snmp/mibs/* /usr/share/snmp/mibs/
            - run:
                command: |
                    mvn -B test -Pskip -DargLine="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-11
                    MAVEN_OPTS: "-Xmx512m"
            - store_test_results:
                path: target/surefire-reports
    testsj8:
        docker:
            - image: circleci/openjdk:8-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
                    sudo mkdir -p /usr/share/snmp/mibs/
                    sudo mv -n /tmp/ws/usr/share/snmp/mibs/* /usr/share/snmp/mibs/
            - run:
                command: |
                    mvn -B test -Pskip -DargLine="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-8
                    MAVEN_OPTS: "-Xmx512m"
            - store_test_results:
                path: target/surefire-reports
    publish:
        docker:
            - image: circleci/openjdk:14-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    mvn -B deploy -Pskip -Dmaven.test.skip=true -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/java/openjdk-14
                    MAVEN_OPTS: "-Xmx2048m"
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
    savecache:
        docker:
            - image: circleci/openjdk:14-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv /tmp/ws/home/circleci/project/pom.xml /home/circleci/project/
                    mv /tmp/ws/home/circleci/.m2 /home/circleci/
            - save_cache:
                paths:
                    - /home/circleci/.m2/repository
                    - /home/circleci/.sonar/cache
                key: jrds-{{ checksum "pom.xml" }}-{{ checksum "jrds-core/pom.xml" }}-{{ checksum "jrds-ipmi/pom.xml" }}-{{ checksum "jrds-jsonp/pom.xml" }}-{{ checksum "jrds-log4j/pom.xml" }}-{{ checksum "jrds-snmp/pom.xml" }}-{{ checksum "jrds-standalone/pom.xml" }}-{{ checksum "jrds-webapp/pom.xml" }}
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout
      - jdk8
      - build:
          requires:
              - checkout
              - jdk8
      - testsj13:
          requires:
              - build
      - testsj11:
          requires:
              - build
      - testsj8:
          requires:
              - build
      - publish:
          requires:
              - testsj13
              - testsj11
              - testsj8
      - savecache:
          requires:
              - publish
